### ISSUE TITLE
ModuleNotFoundError: No module named 'django.core.urlresolvers' error

### ISSUE THREAD

**Issue by itsmeakhil** [ekonstantinidis/django-rest-framework-docs#184]

**Comment by itsmeakhil** [comment]
No idea what can we do to resolve this

**Comment by Bhupesh-V** [comment]
I got the same error

**Comment by presto-wei** [comment]
just now,  i also find the mistake

**Comment by ajeema** [comment]
This is because Django 2.0 removes the django.core.urlresolvers module. I believe now it is from django.urls import include, re_path. I could be wrong

**Comment by suhailvs** [comment]
i have forked this repo(https://github.com/suhailvs/drfrequests) and fixed this issue. it will work with latest djangorestframework.
