### ISSUE TITLE
AttributeError - module 'urls' has no attribute 'urls'

### ISSUE THREAD

**Issue by poswald** [ekonstantinidis/django-rest-framework-docs#32]
My understanding is that there are [two common settings](https://github.com/search?q=ROOT_URLCONF&type=Code&utf8=✓) of `ROOT_URLCONF` people use. One is the default `ROOT_URLCONF = ''` value, and the second is `ROOT_URLCONF = 'urls'`. This project seems to fail if you use the latter (or at least it did for me). Changing that line to         `self.get_all_view_names(root_urlconf.urlpatterns)` worked but it would be best to fix in the project.

The root urlconf can also be [overridden at runtime via middleware](https://docs.djangoproject.com/en/1.9/topics/http/urls/#how-django-processes-a-request) so I think this urls module loading should perhaps be moved into the `get_endpoints` method or the value of that setting should be passed into the `ApiDocumentation` object on init.

Nice project BTW. :-)

**Comment by ekonstantinidis** [comment]
Hi @poswald! I remember having this issue while I was writing some tests for the package. So I was thinking that a check like the one below would make sense?

        if hasattr(root_urlconf, 'urls'):
            self.get_all_view_names(root_urlconf.urls.urlpatterns)
        else:
            self.get_all_view_names(root_urlconf.urlpatterns)

I can confirm that it works when `ROOT_URLCONF = 'project.urls'`
Can you check if it works with your project?

Thank you!

**Comment by poswald** [comment]
Yes it does. I think adding a check like that is fine for now. I do suggest looking into supporting runtime-specified configurations though as I think people use them to do things like having different url schemes for different types of users.

**Comment by ekonstantinidis** [comment]
Yeap let's go with that check for now :+1:
I've just published `0.0.5` to pypi so it should work now! Let me know if it does not!

**Comment by poswald** [comment]
It works, you just need to push the changelog. :-) Thanks.

**Comment by ekonstantinidis** [comment]
Done! :smile: http://drfdocs.com/docs/changelog/
