### ISSUE TITLE
Double-slashes in endpoint URLs

### ISSUE THREAD

**Issue by guitarmanvt** [ekonstantinidis/django-rest-framework-docs#49]
I installed drfdocs with the current DRF tutorial code. I noticed these odd URLs listed in the Docs:
```
//
//snippets/
//snippets/<pk>/highlight/
```
And others.

This is because of this URL configuration in the project-level *urls.py*:

```python
urlpatterns = [
...
    url(r'^', include('snippets.urls')),
...
]
```

*drfdocs* needs to collapse these slashes into one.

**Comment by ekonstantinidis** [comment]
Fixed in #56.
