### ISSUE TITLE
Middle slash removed by "replace"

### ISSUE THREAD

**Issue by philngo** [ekonstantinidis/django-rest-framework-docs#54]
In an DRF router endpoint I'm seeing the following behavior:

    url(r'^api/v1/', include(router.urls)), # becomes "apiv1" in DRF docs output

Not sure exactly sure why slashes are being replaced on this line, but perhaps a `strip('/')` than `replace('/','')`would be more appropriate, as that would preserve slashes in the middle, like I need.

https://github.com/ekonstantinidis/django-rest-framework-docs/blob/9a85323c4147ec4ebb754a8b0373c956ee89b821/rest_framework_docs/api_endpoint.py#L1

Happy to make a PR

**Comment by ekonstantinidis** [comment]
Hello @philngo! I've opened a PR to cover the case where:

    url(r'^', include(router.urls)),

It would be great if you can check whether this works for your project. Thank you!

**Comment by Laptopmini** [comment]
I have the same problem. Tried the code from PR #56 but it did not solve it.

**Comment by ekonstantinidis** [comment]
@philngo @Laptopmini Can you provide me with a `urls.py` example so I can reproduce this issue? Additionally feel free to open a PR!

**Comment by Afnarel** [comment]
Hi! I just created the pull request above (PR #64 ) which should fix the issue.
I had the same problem and it is now working properly.

The pull requests removes only leading and trailing slashes from the parent URL instead of removing all slashes.

**Comment by ekonstantinidis** [comment]
@Afnarel 's PR is now merged so it should be fixed now :+1:
