### ISSUE TITLE
API information empty

### ISSUE THREAD

**Issue by Laptopmini** [ekonstantinidis/django-rest-framework-docs#57]
I am currently having this issue where some of the APIs have empty parameters and are classified in a group called None.

Here is a screenshot: http://i.imgur.com/2pXFhLj.png

Here are the APIs that seem to be incompatible:
`url(r'^api-token-auth/', rest_views.obtain_auth_token),`
`url(r'^api/v1/auth/login/$', LoginView.as_view(), name='login'),`
`url(r'^api/v1/ios/auth/login/$', LoginView.as_view()),`
`url(r'^api/v1/auth/logout/$', LogoutView.as_view(), name='logout'),`
`url(r'^api/v1/ios/auth/logout/$', LogoutView.as_view()),`

Also, is there a way to create "Groups" of APIs manually to organize the page more? 

Many Thanks!

**Comment by ekonstantinidis** [comment]
Hello @Laptopmini!

About the files missing: Are you using `APIView`s? If so I think it is not possible for DRF Docs to pickup the fields. Maybe in the near future you will be able to pass the fields in the docstring!

Currently it is not possible to create Groups manually. I am planning to fix some really important bugs (`ModelViewSets` etc) so I guess we can leave this one for a later stage?

**Comment by debnet** [comment]
Fixed in #70.

**Comment by choi-hye-min** [comment]
이 문제의 답을 찾고 있었습니다.
아직 계획중이군요
