### ISSUE TITLE
"urls doesn't look like a module path" for settings.ROOT_URLCONF

### ISSUE THREAD

**Issue by ckcollab** [ekonstantinidis/django-rest-framework-docs#72]
Heyoo, thanks so much for releasing this!

I seem to be having a problem based on this setting:
`ROOT_URLCONF = 'urls'`

```
  File "/Users/eric/.virtualenvs/image_first/lib/python3.5/site-packages/rest_framework_docs/views.py", line 17, in get_context_data
    docs = ApiDocumentation()
  File "/Users/eric/.virtualenvs/image_first/lib/python3.5/site-packages/rest_framework_docs/api_docs.py", line 12, in __init__
    root_urlconf = import_string(settings.ROOT_URLCONF)
  File "/Users/eric/.virtualenvs/image_first/lib/python3.5/site-packages/django/utils/module_loading.py", line 18, in import_string
    six.reraise(ImportError, ImportError(msg), sys.exc_info()[2])
  File "/Users/eric/.virtualenvs/image_first/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/eric/.virtualenvs/image_first/lib/python3.5/site-packages/django/utils/module_loading.py", line 15, in import_string
    module_path, class_name = dotted_path.rsplit('.', 1)
ImportError: urls doesn't look like a module path
```

Changing to this works:
`ROOT_URLCONF = 'src.urls'`

**Comment by andrewyoung1991** [comment]
the path to your urlconf should be relative to the *manage.py* file (e.g. the `BASE_DIR` setting defined in settings.py). so if your project is named *src* and your directory structure is standard:
``` shell
src/
  manage.py
  src/
    settings.py
    wsgi.py
    urls.py
```
then your `ROOT_URLCONF` setting should be *'src.urls'*.

this is a standard Django setting and is the [default path generated](https://github.com/django/django/blob/master/django/conf/project_template/project_name/settings.py-tpl#L52) by the `django-admin.py startproject` command.

I hope this answers your question.

**Comment by ambivalentno** [comment]
I have to note that it's not a "standard", but a "default", as there's an option to provide a template for ```startproject``` command.
For instance, I've got such project layout:

```
project/
├── apps
│   ├── core
│   │   ├── admin.py
│   │   ├── apps.py
│   │   ├── __init__.py
│   │   ├── migrations
│   │   │   ├── 0001_initial.py
│   │   │   └── __init__.py
│   │   ├── models.py
│   │   ├── serializers.py
│   │   ├── urls.py
│   │   └── views.py
│   └── __init__.py
├── conf
│   ├── base.py
│   ├── __init__.py
│   └── local.example.py
├── db
│   └── development.db
├── __init__.py
├── manage.py
├── templates
│   └── base.html
├── urls.py
└── wsgi.py
```

So, I'm researching this at the moment, as I've got urls in the same place as manage.py file :)

**Comment by ambivalentno** [comment]
looks like this works (in api_docs.py):

```
try:
            root_urlconf = import_string(settings.ROOT_URLCONF)
        except ImportError:
            from importlib import import_module
            root_urlconf = import_module(settings.ROOT_URLCONF)
```

**Comment by ambivalentno** [comment]
pullrequest https://github.com/ekonstantinidis/django-rest-framework-docs/pull/73

**Comment by ekonstantinidis** [comment]
@andrewyoung1991 Does #73 solve the problem for you too?

**Comment by andrewyoung1991** [comment]
works for me.

**Comment by ekonstantinidis** [comment]
Great! Let's merge it in!

**Comment by ckcollab** [comment]
Thanks for all the work on this boys :dancers:

**Comment by ekonstantinidis** [comment]
@ckcollab @ambivalentno Version 0.0.9 is now on PyPI :clap:
